
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shamal.gomes
 */
public class Design extends javax.swing.JFrame {
    
     double number = 0.0;    
     int numZero;
     int numOne;
     int numTwo;
     int numThree;
     int numFour;
     int numFive;
     int numSix;
     int numSeven;
     int numEight;
     int numNine;
     String operator = null;
     int total = 0;
     String user_input_number1 = "";
     String user_input_number2 = "";
     String store;
     String store1;
    String store2;
    String store3;
    String store4;
    String store5;
    String store6;
    String store7;
    String store8;
    String store9;
    String store10;
    Boolean MSClick=false;
    Boolean RRClicked=false;
    
    /**
     * Creates new form Design
     */
    public Design() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        txtDisplay = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnSeven = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnMultiply = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MPlus = new javax.swing.JButton();
        MMinus = new javax.swing.JButton();
        MRecall = new javax.swing.JButton();
        MClear = new javax.swing.JButton();
        txtDisplayE = new javax.swing.JTextField();
        MClear1 = new javax.swing.JButton();
        Recall = new javax.swing.JButton();

        jButton7.setText("jButton1");

        jButton8.setText("jButton1");

        jButton9.setText("jButton1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton14.setText("1");

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton13.setText("=");

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-5-icon.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-9-icon.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        txtDisplay.setBackground(java.awt.Color.black);
        txtDisplay.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtDisplay.setForeground(new java.awt.Color(51, 255, 51));
        txtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplayActionPerformed(evt);
            }
        });

        btnSeven.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnSeven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-7-icon.png"))); // NOI18N
        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnNine.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnNine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-9-icon.png"))); // NOI18N
        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnEight.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnEight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-8-icon.png"))); // NOI18N
        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnFour.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnFour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-4-icon.png"))); // NOI18N
        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnFive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-5-icon.png"))); // NOI18N
        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnOne.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        btnOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-1-icon.png"))); // NOI18N
        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnTwo.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-2-icon.png"))); // NOI18N
        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnThree.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-3-icon.png"))); // NOI18N
        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnZero.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnZero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-0-icon.png"))); // NOI18N
        btnZero.setText("0");
        btnZero.setToolTipText("");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnEqual.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnEqual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Math-equal-icon (1).png"))); // NOI18N
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnSix.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnSix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number-6-icon.png"))); // NOI18N
        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnMultiply.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnMultiply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Math-multiply-icon.png"))); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Math-plus-icon.png"))); // NOI18N
        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDivide.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnDivide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Math-divide-icon.png"))); // NOI18N
        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnMinus.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Math-minus-icon.png"))); // NOI18N
        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton1.setText("AC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock-vector-illustration-of-a-solar-cell-pattern-eps-vector-81932260.jpg"))); // NOI18N
        jButton17.setText("jButton17");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("FX-845 Plus");

        MPlus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MPlus.setText("M+");
        MPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPlusActionPerformed(evt);
            }
        });

        MMinus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MMinus.setText("M-");
        MMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMinusActionPerformed(evt);
            }
        });

        MRecall.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MRecall.setText("MR");
        MRecall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRecallActionPerformed(evt);
            }
        });

        MClear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MClear.setText("MC");
        MClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MClearActionPerformed(evt);
            }
        });

        txtDisplayE.setBackground(new java.awt.Color(204, 204, 204));
        txtDisplayE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtDisplayE.setForeground(new java.awt.Color(51, 255, 51));
        txtDisplayE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplayEActionPerformed(evt);
            }
        });

        MClear1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MClear1.setText("MS");
        MClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MClear1ActionPerformed(evt);
            }
        });

        Recall.setText("RR");
        Recall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDisplayE, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Recall)
                        .addGap(33, 33, 33)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MPlus)
                .addGap(18, 18, 18)
                .addComponent(MMinus)
                .addGap(18, 18, 18)
                .addComponent(MRecall)
                .addGap(18, 18, 18)
                .addComponent(MClear)
                .addGap(18, 18, 18)
                .addComponent(MClear1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Recall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDisplayE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MPlus)
                    .addComponent(MMinus)
                    .addComponent(MRecall)
                    .addComponent(MClear)
                    .addComponent(MClear1))
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
         String fullText = txtDisplay.getText() + btnNine.getText();
 numNine = Integer.parseInt(btnNine.getText());
 if (MSClick==true){
    fullText=null;
    store1= txtDisplay.getText();
    MSClick=false;
   }else
    if(operator == null){
    user_input_number1= user_input_number1 + btnNine.getText();
    }else{ 
        user_input_number2= user_input_number2 + btnNine.getText();
    }
 if(RRClicked==true){
    txtDisplay.setText(store1);
}else
txtDisplay.setText( fullText );
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
 String fullText = txtDisplay.getText() + btnSix.getText();
 numSix = Integer.parseInt(btnSix.getText());
 if (MSClick==true){
    fullText=null;
    store2= txtDisplay.getText();
    MSClick=false;
   }else
 if(operator == null){
    user_input_number1= user_input_number1 + btnSix.getText();
    }else{ 
        user_input_number2= user_input_number2 + btnSix.getText();
    }
if(RRClicked==true){
    txtDisplay.setText(store2);
}else
txtDisplay.setText( fullText );
    }//GEN-LAST:event_btnSixActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
     String fullText = txtDisplay.getText() + btnThree.getText();
  numThree = Integer.parseInt(btnThree.getText());
  if (MSClick==true){
    fullText=null;
    store3= txtDisplay.getText();
    MSClick=false;
   }else
  if(operator == null){
    user_input_number1= user_input_number1 + btnThree.getText();
    }else{ 
        user_input_number2= user_input_number2 + btnThree.getText();
    }
if(RRClicked==true){
    txtDisplay.setText(store3);
}else
txtDisplay.setText( fullText );
    }//GEN-LAST:event_btnThreeActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
       String btnMultiplyText = txtDisplay.getText() + btnMultiply.getText();
       txtDisplay.setText(btnMultiplyText);
       operator = btnMultiply.getText();

    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String btnAddText = txtDisplay.getText() + btnAdd.getText();
        txtDisplay.setText(btnAddText);
        operator = btnAdd.getText();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        String btnDivideText = txtDisplay.getText() + btnDivide.getText();
        txtDisplay.setText(btnDivideText);
        operator = btnDivide.getText();

    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        String btnMinusText = txtDisplay.getText() + btnMinus.getText();
        txtDisplay.setText(btnMinusText);
        operator = btnMinus.getText();

    }//GEN-LAST:event_btnMinusActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        calculate();
        String str = Integer.toString(total);
        txtDisplay.setText(str);
        user_input_number2 = "";
       
               
    }//GEN-LAST:event_btnEqualActionPerformed

    private void calculate() {
        if (store == null ){ 
        switch (operator) {
             case "+":
                 total = Integer.parseInt(user_input_number1)+ Integer.parseInt(user_input_number2);
                 break;
             case "-":
                 total = Integer.parseInt(user_input_number1)- Integer.parseInt(user_input_number2);
                 break;
             case "*":
                 total = Integer.parseInt(user_input_number1)* Integer.parseInt(user_input_number2);
                 break;
             case "/":
                 total = Integer.parseInt(user_input_number1)/ Integer.parseInt(user_input_number2);
                 break;
         }
         user_input_number1 = Integer.toString(total);                 
    }else{
            switch (operator) {
             case "+":
                 total = Integer.parseInt(store)+ Integer.parseInt(user_input_number2);
                 break;
             case "-":
                 total = Integer.parseInt(store)- Integer.parseInt(user_input_number2);
                 break;
             case "*":
                 total = Integer.parseInt(store)* Integer.parseInt(user_input_number2);
                 break;
             case "/":
                 total = Integer.parseInt(store)/ Integer.parseInt(user_input_number2);
                 break;
        }
    }
    }
    private void memoryP(){
        store = (txtDisplay.getText());
        String display = "M" ;
        txtDisplayE.setText(display);
    }
    private void memoryR(){
       txtDisplay.setText(String.valueOf(store));
    }
    private void memoryC(){
        store = "" ;
        store1 = "";
        store2 = "";
        store3 = "";
        store4 = "";
        store5 = "";
        store6 = "";
        store7 = "";
        store8 = "";
        store9 = "";
        store10= "";
        String display = "";
        txtDisplayE.setText(display);
    }
    private void memoryM(){
        String display = "M" ;
        txtDisplayE.setText(display);
        String x = txtDisplay.getText();
        int y = Integer.parseInt(x)*-1 ;
        store = (String.valueOf(y));
        
    }
    private void memoryS(){
     MSClick=true;
     String display = "MS" ;
        txtDisplayE.setText(display);
    }
    
         
        

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed

 String fullText = txtDisplay.getText() + btnOne.getText();
numOne = Integer.parseInt( btnOne.getText());
if (MSClick==true){
    fullText=null;
    store4= txtDisplay.getText();
    MSClick=false;
   }else
 if(operator == null){
    user_input_number1= user_input_number1 + btnOne.getText();
    }else{ 
        user_input_number2= user_input_number2 + btnOne.getText();
    }
if(RRClicked==true){
    txtDisplay.setText(store4);
}else
 txtDisplay.setText(fullText);
    }//GEN-LAST:event_btnOneActionPerformed

    private void txtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayActionPerformed

        
    }//GEN-LAST:event_txtDisplayActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
String fullText = txtDisplay.getText() + btnTwo.getText();
numTwo = Integer.parseInt(btnTwo.getText());
if (MSClick==true){
    fullText=null;
    store5= txtDisplay.getText();
    MSClick=false;
   }else
if(operator == null){
    user_input_number1= user_input_number1 + btnTwo.getText();
    }else{ 
        user_input_number2= user_input_number2 + btnTwo.getText();
    }
 if(RRClicked==true){
    txtDisplay.setText(store5);
}else
txtDisplay.setText( fullText );   

    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
 String fullText = txtDisplay.getText() + btnFour.getText();
 numFour = Integer.parseInt(btnFour.getText());
 if (MSClick==true){
    fullText=null;
    store6= txtDisplay.getText();
    MSClick=false;
   }else
 if(operator == null){
    user_input_number1= user_input_number1 + btnFour.getText();
    }else{ 
        user_input_number2= user_input_number2 + btnFour.getText();
    }
if(RRClicked==true){
    txtDisplay.setText(store6);
}else
txtDisplay.setText( fullText );

    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
String fullText = txtDisplay.getText() + btnFive.getText();
numFive = Integer.parseInt(btnFive.getText());
if (MSClick==true){
    fullText=null;
    store7= txtDisplay.getText();
    MSClick=false;
   }else
if(operator == null){
    user_input_number1= user_input_number1 + btnFive.getText();
    }else{ 
        user_input_number2= user_input_number2 + btnFive.getText();
    }
 if(RRClicked==true){
    txtDisplay.setText(store7);
}else
txtDisplay.setText( fullText );

    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
 String fullText = txtDisplay.getText() + btnSeven.getText();
numSeven = Integer.parseInt(btnSeven.getText());
if (MSClick==true){
    fullText=null;
    store8= txtDisplay.getText();
    MSClick=false;
   }else
if(operator == null){
    user_input_number1= user_input_number1 + btnSeven.getText();
    }else{ 
        user_input_number2= user_input_number2 + btnSeven.getText();
    }
 if(RRClicked==true){
    txtDisplay.setText(store8);
}else
txtDisplay.setText( fullText );

    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
 String fullText = txtDisplay.getText() + btnEight.getText();
 numEight = Integer.parseInt(btnEight.getText());
 if (MSClick==true){
    fullText=null;
    store9= txtDisplay.getText();
    MSClick=false;
   }else
 if(operator == null){
    user_input_number1= user_input_number1 + btnEight.getText();
    }else{ 
        user_input_number2= user_input_number2 + btnEight.getText();
 }
txtDisplay.setText( fullText );
if(RRClicked==true){
    txtDisplay.setText(store9);
}
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        String fullText = txtDisplay.getText() + btnZero.getText();
        numZero = Integer.parseInt(btnZero.getText());
        if (MSClick==true){
    fullText=null;
    store10= txtDisplay.getText();
    MSClick=false;
   }else
        if(operator == null){
    user_input_number1= user_input_number1 + btnZero.getText();
    }else{ 
        user_input_number2= user_input_number2 + btnZero.getText() ;
        }
txtDisplay.setText( fullText );
if(RRClicked==true){
    txtDisplay.setText(store10);
}
   
    }//GEN-LAST:event_btnZeroActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
total=0;
operator=null;
user_input_number1 = "";
user_input_number2 = "";
txtDisplay.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MRecallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRecallActionPerformed
memoryR();
    }//GEN-LAST:event_MRecallActionPerformed

    private void MPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPlusActionPerformed
memoryP();     
    }//GEN-LAST:event_MPlusActionPerformed

    private void MClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MClearActionPerformed
memoryC();
    }//GEN-LAST:event_MClearActionPerformed

    private void MMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMinusActionPerformed
memoryM();
    }//GEN-LAST:event_MMinusActionPerformed

    private void txtDisplayEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayEActionPerformed

    }//GEN-LAST:event_txtDisplayEActionPerformed

    private void MClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MClear1ActionPerformed
memoryS();
    }//GEN-LAST:event_MClear1ActionPerformed

    private void RecallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecallActionPerformed
        RRClicked=true;
    }//GEN-LAST:event_RecallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Design().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MClear;
    private javax.swing.JButton MClear1;
    private javax.swing.JButton MMinus;
    private javax.swing.JButton MPlus;
    private javax.swing.JButton MRecall;
    private javax.swing.JButton Recall;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDisplay;
    private javax.swing.JTextField txtDisplayE;
    // End of variables declaration//GEN-END:variables
}
